app/manifest.yml
app/package.json
app/src/check-permissions.ts
app/src/resolvers.ts
app/yarn.lock

Add permission check before every resolver func so that only administrators can access these methods.
If user is not an admin, they will see an error on the console, or an infinitely loading web page (they should not be able to access the app UI unless they are an admin, so this is not an issue)

ARC-1414 Add isAdmin check at the start of every resolver func

---

app/jenkins-for-jira-ui/src/components/ConnectJenkins/ConfigurationSteps/ConfigurationSteps.test.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/ConfigurationSteps/ConfigurationSteps.tsx

**Context**
Due to a confusing Jenkins server connection flow, we have decided to split the Jenkins server connection flow into 3 steps. For more information, [see here](https://hello.atlassian.net/wiki/spaces/PF/pages/1793379128/JFA+ARC-1264+-+Split+Connection+Screen+plan+and+ideation).
**Changes in this PR**
We are splitting the server connection screen and need to update the progress tracker to include 3 steps. This PR leverages the AtlasKit [Progress Tracker](https://atlassian.design/components/progress-tracker/examples) to create a progress tracker that takes you through connecting a Jenkins server to your Jira. The `ConfigurationSteps` component takes in a `currentStage` prop and returns the progress tracker at the appropriate stage.
**From 2 steps:**
**To 3 steps:**
On install …

ARC-1584 Update ConfigurationSteps component to have 3 steps

---

app/jenkins-for-jira-ui/src/App.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/CreateServer/CreateServer.test.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/CreateServer/CreateServer.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/InstallJenkins/InstallJenkins.tsx
app/jenkins-for-jira-ui/src/components/JenkinsConfigurationForm/ServerConfigurationFormElements/ServerConfigurationFormName/ServerConfigurationFormName.tsx

**Context**
Due to a confusing Jenkins server connection flow, we have decided to split the Jenkins server connection flow into 3 steps. For more information, [see here](https://hello.atlassian.net/wiki/spaces/PF/pages/1793379128/JFA+ARC-1264+-+Split+Connection+Screen+plan+and+ideation).
**Changes in this PR**
This PR adds a `CreateServer` component that allows the customer to create a Jenkins Server with the name of their choice. When you press "Next", the button will switch into a loading state and create the server. It will then move on to the "Connect Jenkins" screen.
Error state
Loading state
**Tasks to be completed**
Currently, when you move on to the "Connect Jenkins" screen, your server details are not passed through. This means that the second screen will just create a new …

ARC-1264 Add create server step to server connection flow

---

app/jenkins-for-jira-ui/src/App.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/ConfigurationSteps/ConfigurationSteps.test.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/ConfigurationSteps/ConfigurationSteps.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/ConnectJenkins/ConnectJenkins.test.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/ConnectJenkins/ConnectJenkins.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/CreateServer/CreateServer.tsx
app/jenkins-for-jira-ui/src/components/JenkinsConfigurationForm/ServerConfigurationFormElements/ServerConfigurationFormName/ServerConfigurationFormName.tsx

**Context**
Due to a confusing Jenkins server connection flow, we have decided to split the Jenkins server connection flow into 3 steps. For more information, [see here](https://hello.atlassian.net/wiki/spaces/PF/pages/1793379128/JFA+ARC-1264+-+Split+Connection+Screen+plan+and+ideation).
**Changes in this PR**
This PR passes newly created server id to the `ConnectJenkins` component (step 3 in the workflow), and has it display the newly created server details.
Create server - Step 2:
Connect server - Step 3: 
When clicking "Done" on the "Connect server" screen, it will update any details you provide it.
Note: I have ensured that the title and steps are still rendered when retrieving the server details on the "Connect server" screen. This makes for a smoother transition between the steps. …

ARC-1264 Update ConnectJenkins component to take in and display connected server details

---

app/jenkins-for-jira-ui/src/components/JenkinsConfigurationForm/ServerConfigurationFormElements/ServerConfigurationFormName/ServerConfigurationFormName.tsx

**Context**
Due to a confusing Jenkins server connection flow, we have decided to split the Jenkins server connection flow into 3 steps. For more information, [see here](https://hello.atlassian.net/wiki/spaces/PF/pages/1793379128/JFA+ARC-1264+-+Split+Connection+Screen+plan+and+ideation).
**Changes in this PR**
This PR updates the copy for the server name form tooltip.

ARC-1667 Update copy for the server name tooltip

---

.gitignore
renovate.json

Updated renovate.json so that Jenkins has it's own configuration. We were previously pointing to the main config that's also used by DSS, but that's now been updated so Renovate can automatically merge patch bumps to master. DSS is fairly reliable, and has solid CICD, so we do not want to allow the bot to do this automatically for Jenkins at this point in time.

ARC-437 update renovate config

---

.husky/pre-commit
app/jenkins-for-jira-ui/src/api/disconnectJenkinsServer.ts
app/package.json
app/yarn.lock

Addition of a pre commit hook.
**Why**
The app errors instantly when there's an error but we currently have zero checks in place anywhere else. No linting checks on commit and no workflows to run tests. Veeeeeeery easy for something to slip through.
ARC-2263
When I committed.
ARC-2261 - set up some workflows to run tests so we block merging if anything fails.

Arc-2263 pre commit hooks

---

app/jenkins-for-jira-ui/src/api/getAllJenkinsServers.ts
app/jenkins-for-jira-ui/src/common/analytics/analytics-events.ts
app/jenkins-for-jira-ui/src/components/JenkinsServerList/PendingDeploymentState/PendingDeploymentState.styles.tsx
app/jenkins-for-jira-ui/src/components/JenkinsServerList/PendingDeploymentState/PendingDeploymentState.tsx

Added a back button to the pending state screen.
**Why**
There's no way to navigate back (apart from browser buttons)
ARC-2262
Locally
https://github.com/atlassian/jenkins-for-jira/assets/37155488/757bcc1d-0016-4d87-a063-84f6a9c95def
Was going to add a test but then realised there's no tests at all currently for this page. Created [ARC-2300](https://softwareteams.atlassian.net/jira/software/projects/ARC/boards/385/backlog?selectedIssue=ARC-2300) to add a coverage reporter and then add additional tests to where they are most needed.
[ARC-2300]: https://softwareteams.atlassian.net/browse/ARC-2300

add back button to pending state screen

---

app/manifest.yml

Addition of useAsGetStarted to manifest
**Why**
To expose the Get started button when you go to manage apps and to expose the Get started link in the flag.
ARC-2412
Locally

ARC-2412 add useAsGetStarted prop

---

app/jenkins-for-jira-ui/src/components/ConnectJenkins/CreateServer/CreateServer.tsx
app/jenkins-for-jira-ui/src/components/JenkinsConfigurationForm/JenkinsConfigurationForm.tsx

Removing FF to generate the secret on the backend vs frontend.
**Why**
Coz it's been at 100% for a couple of weeks and all looks good. And we need to remove these bad boys once we're done with them :_wink:
Nah, just removing one
NONE
Locally
Delete the actual feature flag :excellentburnsgif:

NONE remove ff for generating secret on backend

---

app/jenkins-for-jira-ui/src/api/fetchCloudId.test.ts
app/jenkins-for-jira-ui/src/api/fetchCloudId.ts
app/src/resolvers.ts

Added a new resolver
**Why**
So the client can make a request to get the cloudId by doing something like:
```
const getCloudId = async (): Promise<void> => {
const id = await fetchCloudId() || '';
setCloudId(id);
};
useEffect(() => {
getCloudId();
}, []);
```
n/a
ARC-2585
Locally
auto deployments!

add resolver to pass cloud id

---

app/src/config/env.ts
app/src/config/feature-flags.ts

Added a custom env var
**Why**
Forge doesn't play nice with NODE_ENV and overrides it in every environment with 'production' :sigh:
n/a
none
Tested development and staging environments via the official Jenkins app and could see in the logs I'm getting the values I should get from LD. Tested prod as well by registering my own app and deploying it to production. Logs there looked good too.
Pray that Forge stop throwing me curveballs.

NONE add custom env var

---

app/jenkins-for-jira-ui/src/components/MainPage/MainPage.styles.tsx

Updated styling to use token for spacing.
**Why**
To make sure we're doing things the Atlassian way 🙃 
nah
nope
locally. looks legit
:work-harder:

NONE add token to new style files

---

app/jenkins-for-jira-ui/src/App.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectedJenkinsServers.test.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectedJenkinsServers.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.styles.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.tests.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelMain.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelTop.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/SetUpGuide.tsx
app/jenkins-for-jira-ui/src/components/MainPage/MainPage.tsx
app/src/common/types.ts

Connected state component that will be used in both the admin and global pages.
If a pipeline ran within the last 24 hours you'll see the time formatted like:
Otherwise, it will look like:
**Why**
Coz it wasn't done yet?
All behind RENOVATED_JENKINS_FOR_JIRA_CONFIG_FLOW
Arc-2676
Locally and staging
* Consume data from the backend, update existing dummy data, and write tests for set up guide (didn't do it when I created the set up guide component as I would have to change the tests once real data was flowing in)
* A loader will be added when I build the connection wizard for the empty state

Arc-2676 connected state

---

app/README.md
app/jenkins-for-jira-ui/.gitignore

Added browser none to env vars to stop this stupid tab from opening every time we spin up the frontend.
https://github.com/atlassian/jenkins-for-jira/assets/37155488/30696e08-092e-495a-8858-f8fe99d932f4
Oh and ripped out .env.example coz it was empty. Probably not the best example for any wannabe contributors.
**Why**
I think the question here should be: 'why didn't you do this sooner?' 
Locally... coz that's the only place it happens... :awkward_sus:
Back to actual work.

add browser none to stop tab from opening

---

app/jenkins-for-jira-ui/src/App.tsx
app/jenkins-for-jira-ui/src/GlobalStyles.styles.tsx
app/jenkins-for-jira-ui/src/common/util/jenkinsConnectionsUtils.ts
app/jenkins-for-jira-ui/src/components/ConnectionWizard/ConnectionFlowHeader.tsx
app/jenkins-for-jira-ui/src/components/ConnectionWizard/ConnectionWizard.styles.tsx
app/jenkins-for-jira-ui/src/components/ConnectionWizard/ConnectionWizard.tsx
app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.tsx
app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.styles.tsx
app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.test.tsx
app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.tsx

Server name screen: empty state when there are no servers/connect a new server from configured screen.
Input empty (disabled button)
Input added (button active)
Error state (new check to see if the server name already exists)
**Why**
So users can create servers from an empty/configured state
same as always
Arc-2595
Locally, tests, stg
The next screen :hyperblob:

Arc-2595 server name screen

---

app/jenkins-for-jira-ui/package.json
app/jenkins-for-jira-ui/src/App.tsx
app/jenkins-for-jira-ui/src/components/ConnectJenkins/ConnectJenkins/ConnectJenkins.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.test.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelContent.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelMain.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelTop.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/NotConnectedState.test.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/NotConnectedState.tsx
app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.tsx
app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.tsx
app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.tsx
app/jenkins-for-jira-ui/yarn.lock

More fixes and tidy up after wrapping up my own testing blitz 😄 
- updated the Connection settings flow so that users click 'Done' and are then navigated back to the config screen instead of the through the rest of the server creation flow.
- updated the **Refresh** logic. Noticed it wasn't always playing nice and was resulting in some UI funkiness. Have hammered it locally with servers of all different status types and is now working as it should be

None fix more shit

---

app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.tsx

Content update to the share button copy content.
**Why**
When we changed the scope (permissions) to fix the issues with the Node runtime (forced update by Forge), a major version bump kicked in. This means Jira admins need to manually click the Update button on their manage apps page to accept the new version. Unfortunately, this overlaps with the release of our global page which will only become available once customers are on version 14 or higher. This is an issue as when we begin rolling out the J4J FF, anyone that shares the copy content from the Share page button will be sharing a link to a page that doesn't exist... and currently about 90% of our customers are on an outdated version. 
There is no way for us to make a request from a Forge app to get the version …

update message to account for broken global page link

---

app/jenkins-for-jira-ui/src/api/fetchGlobalPageUrl.ts
app/jenkins-for-jira-ui/src/api/fetchUserPerms.ts
app/src/resolvers.ts
app/src/storage/fetch-user-perms.ts
app/src/utils/fetch-user-perms.ts

Update to the backend and addition of API on the frontend
**Why**
Currently, we're hiding action buttons from all users on the global page but we want admins to see them regardless of whether they are on the admin/global page. To do this, we need to make a request to the backend to get the users permission level. 
This is part 1 - originally had it altogether but the size was getting a little wiley.
check_user_permissions
ARC-2807
Locally and in staging. Needs to go to prod before I can make sure the buttons still aren't visible in the non-admin account coz they don't have access to dev/stg instances. Thank god for feature flags hey? :blobeyebrows:
Get this merged and then …

ARC-2807 - add admin check to global page part 1

---

app/jenkins-for-jira-ui/src/common/analytics/analytics-events.ts
app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelTop.tsx
app/jenkins-for-jira-ui/src/components/ConnectionPanel/NotConnectedState.tsx
app/jenkins-for-jira-ui/src/components/GlobalPage/GlobalPage.tsx
app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.tsx

Added source (page where event was fired) to a few analytics + 1 new analytic
**Why**
Previously certain actions could only be fired on the admin page but, now that we're exposing the buttons for admins on the global page, we need to know where the event is coming from.
nah
NONE
Update the analytic events and register a new one.

NONE update analytics

---

app/src/config/feature-flag.test.ts
app/src/config/feature-flags.ts

ADded a timeout to LD incase of slowness or other network errors
Also made the failure return false instead of throwing an error
With returning false we now default to false instead of hanging for ever

Hot fix LaunchDarkly errors

---

app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelMain.tsx
app/jenkins-for-jira-ui/src/components/GlobalPage/GlobalPage.tsx
app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.test.tsx
app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.tsx
app/jenkins-for-jira-ui/src/components/SharePage/SharePage.test.tsx
app/jenkins-for-jira-ui/src/components/SharePage/SharePage.tsx

Refactoring code to reuse share page component so that it is easier to mange and update component in future. A base step for Jenkins Phase 1.1 Design Improvement task 1.2
ARC-2911
yarn test &
Manual UI testing
In global page
In server management page,
Continue on design 1.2 task, which is updating the share page text content.

global & server management page reuse share page component

---

app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.tsx
app/jenkins-for-jira-ui/src/components/SharePage/SharePage.tsx

Some clean up work after discussion with the Design people to let share page contents all show same text.
**Why**
Before, there are 2 versions of share page content depends on the module key. Now we want to remove dependency on module key and just have all share page content to have the same content.
ARC-2911
yarn test & 
manual testing among the 3 share button page

ARC-2911 let all share page content show the same thing

---

app/src/jira-client/delete-builds.ts

Remove redundant cloudId property for DD endpoint
**Why**
DD want to restrict endpoint to one property
ARC-3241
**Testing**
Tested by deploying to staging and testing disconnection. See Jira ticket for loom.

ARC-3241 Clean BulkByProperties api call to remove cloud id as this is redundant

---

app/src/jira-client/delete-builds.test.ts
app/src/jira-client/delete-builds.ts
app/src/jira-client/delete-deployments.test.ts
app/src/jira-client/delete-deployments.ts
app/src/jira-client/get-gating-status-from-jira.test.ts
app/src/jira-client/get-gating-status-from-jira.ts
app/src/jira-client/send-event-to-jira.test.ts
app/src/jira-client/send-event-to-jira.ts

EDIT: merging PR into a development branch so the changes can be soaked in Staging
* Replaces usages of `requestConnectedData` with `requestJira`
* Replaces request paths to call data depot of format like `/deployments/0.1/cloud/${cloudId}/...` with format `/rest/deployments/0.1/...`
**Why**
`requestJira` is the way that Forge apps should be calling the data depot V1 APIs. This is now publicly documented ([see deployment info provider Forge manifest reference documentation](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-software-deployment-info/)).
As this is an open-source Forge app which other Forge app developers may use as a reference, we want them to use `requestJira`.
Note that `requestJira` Forge function appends …

Replaces requestConnectedData with requestJira

---

app/src/jira-client/delete-builds.test.ts
app/src/jira-client/delete-builds.ts
app/src/jira-client/delete-deployments.test.ts
app/src/jira-client/delete-deployments.ts
app/src/jira-client/get-gating-status-from-jira.test.ts
app/src/jira-client/get-gating-status-from-jira.ts
app/src/jira-client/send-event-to-jira.test.ts
app/src/jira-client/send-event-to-jira.ts

* Replaces usages of `requestConnectedData` with `requestJira`
* Replaces request paths to call data depot of format like `/deployments/0.1/cloud/${cloudId}/...` with format `/rest/deployments/0.1/...`
**Why**
`requestJira` is the way that Forge apps should be calling the data depot V1 APIs. This is now publicly documented ([see deployment info provider Forge manifest reference documentation](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-software-deployment-info/)).
As this is an open-source Forge app which other Forge app developers may use as a reference, we want them to use `requestJira`.
Note that `requestJira` Forge function appends `ex/jira/{cloudId}` to the start of the request. This is why it doesn't need to be provided as a …

Replace `requestConnectedData` with `requestJira`
