- app/README.md
Update Forge App Id to match new marketplace listing
> ARC-1524: Update Forge App Id

- CONTRIBUTING.md
Make it clearer where to find instructions for developing on this app
> noissue: Make the CONTRIBUTING.md clearer

- app/jest-setup.js
- app/jest.config.js
- app/src/webtrigger/handle-reset-jenkins-request.test.ts
- app/src/webtrigger/handle-reset-jenkins-request.ts
- app/src/webtrigger/types.ts
Enhancing pollinator check APIs 
- Adding support to exclude sever from removing all connected Jenkins servers API
- Adding a new API to remove builds and deployments data
> ARC-1844 Fix pollinator check

- app/jenkins-for-jira-ui/src/common/analytics/analytics-client.ts
- app/jenkins-for-jira-ui/src/common/analytics/analytics-events.ts
- app/jenkins-for-jira-ui/src/components/ConnectJenkins/InstallJenkins/InstallJenkins.tsx
- app/jenkins-for-jira-ui/src/components/EmptyState/EmptyState.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsConfigurationForm/JenkinsConfigurationForm.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsConfigurationForm/ServerConfigurationFormElements/ServerConfigurationFormSecret/ServerConfigurationFormSecret.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsServerList/ConnectedServer/ConnectedServers.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsServerList/JenkinsServerList.tsx
- app/jenkins-for-jira-ui/src/components/ManageConnection/ManageConnection.tsx
Added UI events to most things a user can click, excluding form submit buttons (they fall under track events).
Small sampling of some of the UI events added:
https://github.com/atlassian/jenkins-for-jira/assets/37155488/526aeadf-e1fd-4455-be94-2406bf57b917
> Arc-2229 add analytics UI events

- app/jenkins-for-jira-ui/src/common/analytics/analytics-client.ts
- app/jenkins-for-jira-ui/src/common/analytics/analytics-events.ts
- app/jenkins-for-jira-ui/src/components/ConnectJenkins/ConnectJenkins/ConnectJenkins.tsx
- app/jenkins-for-jira-ui/src/components/ConnectJenkins/CreateServer/CreateServer.tsx
- app/jenkins-for-jira-ui/src/components/ManageConnection/ManageConnection.tsx
More analytics but for tracking events this time around.
> Arc-2229 add analytics track events

- app/jenkins-for-jira-ui/src/api/getAllJenkinsServers.ts
- app/jenkins-for-jira-ui/src/common/analytics/analytics-events.ts
- app/jenkins-for-jira-ui/src/components/ConnectJenkins/ConnectJenkins/ConnectJenkins.tsx
- app/jenkins-for-jira-ui/src/components/ConnectJenkins/CreateServer/CreateServer.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsConfigurationForm/JenkinsConfigurationForm.test.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsConfigurationForm/JenkinsConfigurationForm.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsServerList/JenkinsServerList.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsServerList/PendingDeploymentState/PendingDeploymentState.tsx
- app/jenkins-for-jira-ui/src/components/ManageConnection/ManageConnection.tsx
Added some more analytics.
**Why**
I've noticed some gaps while creating charts.
**Affected issues**
ARC-2241
How has this been tested?
Locally with the analytics extension
> ARC-2241: add more analytics events

- app/jenkins-for-jira-ui/src/components/JenkinsServerList/ConnectedServer/ConnectedServers.tsx
Removing servername from the metrics
**Why**
its UGC
> None remove ugc

- app/src/common/error-messages.ts
- app/src/jira-client/delete-builds.test.ts
- app/src/jira-client/delete-builds.ts
- app/src/jira-client/delete-deployments.test.ts
- app/src/jira-client/delete-deployments.ts
- app/src/jira-client/get-gating-status-from-jira.test.ts
- app/src/jira-client/get-gating-status-from-jira.ts
- app/src/jira-client/send-event-to-jira.test.ts
- app/src/jira-client/send-event-to-jira.ts
Tests for Jira client
**Why**
There were none 😬 
ARC-2300
unit tests
- configure feature flags
- logging
- better error handling
- more tests
> Arc-2300 add tests jira client

- app/src/common/error-messages.ts
- app/src/jira-client/delete-builds.test.ts
- app/src/jira-client/delete-deployments.test.ts
- app/src/jira-client/get-gating-status-from-jira.test.ts
- app/src/jira-client/send-event-to-jira.test.ts
- app/src/webtrigger/handle-jenkins-request.ts
Linting fixes (ran the linter fix option)
**Why**
There were a tonne of warnings in the console that were causing too much noise.
Continue with the stuff I'm meant to be working on :badpokerface:
> clean up some linting warnings

- app/src/jira-client/delete-builds.ts
- app/src/jira-client/delete-deployments.ts
- app/src/jira-client/get-gating-status-from-jira.test.ts
- app/src/jira-client/get-gating-status-from-jira.ts
- app/src/jira-client/send-event-to-jira.test.ts
- app/src/jira-client/send-event-to-jira.ts
- app/src/storage/get-jenkins-server-secret.ts
- app/src/storage/get-jenkins-server-with-secret.ts
- app/src/storage/update-jenkins-server-state.test.ts
- app/src/storage/update-jenkins-server-state.ts
- app/src/utils/get-data-from-response.test.ts
- app/src/utils/get-data-from-response.ts
- app/src/webtrigger/handle-jenkins-request.ts
- app/src/webtrigger/handle-reset-jenkins-request.ts
- app/src/webtrigger/jwt.ts
- app/src/webtrigger/webtrigger-utils.ts
Updated the remaining console logs to use the new logger. First pr here https://github.com/atlassian/jenkins-for-jira/pull/144
**Why**
Because...
ARC-2302
Locally
Move onto something else. I'm over thinking about logging. How about you?
> ARC-2302 update logs

- app/manifest.yml
Reverts atlassian/jenkins-for-jira#163
> Revert "Arc-2331 kill jsonwebtoken with fire"

- app/jenkins-for-jira-ui/src/__mocks__/@forge/bridge/index.ts
- app/jenkins-for-jira-ui/src/api/generateNewSecret.test.ts
- app/jenkins-for-jira-ui/src/api/generateNewSecret.ts
- app/jenkins-for-jira-ui/src/common/analytics/analytics-events.ts
- app/jenkins-for-jira-ui/src/components/ConnectJenkins/CreateServer/CreateServer.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsConfigurationForm/JenkinsConfigurationForm.tsx
- app/package.json
- app/src/common/error-messages.ts
- app/src/common/error.ts
- app/src/common/metric-names.ts
- app/src/resolvers.ts
- app/src/storage/generate-new-secret.test.ts
- app/src/storage/generate-new-secret.ts
- app/src/webtrigger/handle-jenkins-request.ts
- app/src/webtrigger/handle-reset-jenkins-request.test.ts
- app/src/webtrigger/handle-reset-jenkins-request.ts
- app/src/webtrigger/jwt.test.ts
- app/src/webtrigger/jwt.ts
- app/yarn.lock
What's in this PR?
Removal of jsonwebtoken
Moved secret generation to backend
Why
jsonwebtoken has a vuln and the way we were generating secrets was insecure
Added feature flags
SERVER_SECRET_GENERATION
Affected issues
Arc-2331
How has this been tested?
Locally - recorded a bunch of scenarios (screenshots for data coming through... too long to record that happening)
**Creating a server with 'old' secret - (on the client)**
https://github.com/atlassian/jenkins-for-jira/assets/37155488/13b7cf36-aaac-44a1-a504-4025ba9c52a9
**Updating an old secret with new logic (ff on, created on backend)**
https://github.com/atlassian/jenkins-for-jira/assets/37155488/e8b39817-a3ef-4ebd-a6a9-33cd4d0d22fb
**Creating a secret the new way - on the backend** …
> Arc 2331 kill jsonwebtoken with fire

- app/src/config/feature-flags.ts
- app/src/config/logger.test.ts
- app/src/config/logger.ts
- app/src/jira-client/delete-builds.ts
- app/src/jira-client/delete-deployments.ts
- app/src/jira-client/get-gating-status-from-jira.ts
- app/src/jira-client/send-event-to-jira.ts
- app/src/storage/connect-jenkins-server.ts
- app/src/storage/disconnect-jenkins-server.ts
- app/src/storage/generate-new-secret.ts
- app/src/storage/get-all-jenkins-servers.ts
- app/src/storage/get-jenkins-server-secret.ts
- app/src/storage/get-jenkins-server-with-secret.ts
- app/src/storage/update-jenkins-server-state.ts
- app/src/storage/update-jenkins-server.ts
- app/src/webtrigger/handle-jenkins-request.ts
- app/src/webtrigger/handle-reset-jenkins-request.ts
- app/src/webtrigger/jwt.test.ts
- app/src/webtrigger/jwt.ts
- app/src/webtrigger/webtrigger-utils.ts
Updated the logger
**Why**
Coz when I first implemented the logger, I tried to follow the pattern that had been used when console logs were being used. Boy was that a stupid idea.
Locally. All looks good.
Feel way less frustrated when adding logs :)
> ARC-2586 cleanup logger

- app/jenkins-for-jira-ui/src/components/JenkinsServerList/JenkinsServerList.tsx
- app/src/utils/extract-app-id-from-local-id.test.ts
- app/src/utils/extract-app-id-from-local-id.ts
- app/src/utils/redirect-from-get-started.test.ts
- app/src/utils/redirect-from-get-started.ts
Updated the appId so it's no longer hardcoded and a small clean up in JenkinsServerList
**Why**
To account for the appId of the outdated app :sigh:
Locally and in staing
Never work with Forge again? One can dream...
> NONE clean up app id

- app/jenkins-for-jira-ui/src/components/JenkinsServerList/JenkinsServerList.tsx
An additional check on the landing page 
**Why**
Coz when the app is configured and we redirect from get-started it looked janky AF
Locally
Pray that Forge starts making things easier?
> add an additional check for redirect nonsense

- app/src/common/types.ts
- app/src/storage/update-jenkins-server-state.test.ts
- app/src/storage/update-jenkins-server-state.ts
- app/src/webtrigger/handle-jenkins-request.test.ts
- app/src/webtrigger/handle-jenkins-request.ts
- app/src/webtrigger/types.ts
Consuming the new PluginConfig event coming from Jenkins plugin, not doing anything special with it,
taking the event data and saving it to storage.
> ARC-2491 listen to pluginconfig event and save to storage

- JenkinsFile
Added a new jenkinsFile so that jenkins can kick off the deployment instead of manual process
> ARC-2282 - added jenkins file

- app/jenkins-for-jira-ui/package.json
Removing duplicate packages
**Why**
Looks like a bad merge when renovate bumped a couple of packages.
> NONE remove duplicate packages... bad renovate

- JenkinsFile
Target master not main for pipelines
> Update JenkinsFile to correct deployment branch

- app/jenkins-for-jira-ui/src/components/ConnectionPanel/NotConnectedState.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/SetUpGuide.tsx
- app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.tsx
- app/jenkins-for-jira-ui/src/components/ServerManagement/TopPanel/TopPanel.tsx
Updated comments
**Why**
Trying to make it more visible/easy to follow so folks know when the TODOs will be cleared up
Actual work?
> NONE make comments clearer

- app/jenkins-for-jira-ui/src/GlobalStyles.styles.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/SetUpGuide.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionWizard/ConnectionWizard.styles.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionWizard/ConnectionWizard.tsx
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelp.styles.tsx
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelpAction.tsx
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelpDrawer.test.tsx
- app/jenkins-for-jira-ui/src/components/InfoPanel/InfoPanel.styles.tsx
- app/jenkins-for-jira-ui/src/components/InfoPanel/InfoPanel.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.styles.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.tsx
Refactored in info panel into a component, updated IPH, and a few minor styling changes to connection wizard.
**Why**
Getting ready for the blitz
_Include how to test if applicable_
> NONE - clean up and refactoring

- app/jenkins-for-jira-ui/.eslintrc.json
- app/jenkins-for-jira-ui/src/common/util/jenkinsConnectionsUtils.ts
- app/jenkins-for-jira-ui/src/components/ConnectionComplete/CompleteConnection.test.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.test.tsx
- app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.styles.tsx
- app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.test.tsx
- app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.tsx
Some more tidy up items.
**Why**
To get things in tip-top shape before the blitz.
1 more clean up PR 😄
> None clean up server name screen

- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelTop.tsx
Added dropdown action for connection settings
**Why**
For excitement
> added connection settings link

- app/jenkins-for-jira-ui/src/components/CopiedToClipboard/CopiedToClipboard.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsServerList/ConnectedServer/JenkinsModal.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.styles.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.tsx
- app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.styles.tsx
Updated the share modal to use the clipboard component and added a new prop to the component for positioning.
Search for more things to clean up.
> None other clean ups

- app/jenkins-for-jira-ui/src/App.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelContent.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelMain.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/NotConnectedState.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/SetUpGuide.tsx
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelp.styles.tsx
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelpAction.tsx
Some more clean up and some fixes.
> None yet more updates

- app/jenkins-for-jira-ui/package.json
- app/package.json
- app/yarn.lock
update packages to help deployments
> update forge metrics

- app/src/jira-client/delete-builds.test.ts
- app/src/jira-client/delete-builds.ts
- app/src/jira-client/delete-deployments.test.ts
- app/src/jira-client/delete-deployments.ts
- app/src/jira-client/get-gating-status-from-jira.test.ts
- app/src/jira-client/get-gating-status-from-jira.ts
- app/src/jira-client/send-event-to-jira.test.ts
- app/src/jira-client/send-event-to-jira.ts
- app/src/resolvers.ts
- app/src/storage/disconnect-jenkins-server.ts
Reverts atlassian/jenkins-for-jira#234
> Revert "Bug update requests api - disconnect button woes"

- app/README.md
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.tsx
1 content change and 1 change to the readme.
Algolia 🙏
> NONE content and readme update

- app/manifest.yml
Include read scope for getgatingstatus
> Update manifest.yml to include read deployment scope

- app/jenkins-for-jira-ui/src/common/analytics/analytics-events.ts
- app/jenkins-for-jira-ui/src/common/constants.ts
- app/jenkins-for-jira-ui/src/components/ConnectionComplete/ConnectionComplete.tsx
Trying to reduce what's going on for the global config stuff.
> NONE small changes

- app/jenkins-for-jira-ui/package.json
- app/jenkins-for-jira-ui/src/App.tsx
- app/jenkins-for-jira-ui/src/GlobalStyles.styles.tsx
- app/jenkins-for-jira-ui/src/common/constants.ts
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/NotConnectedState.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/SetUpGuide.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionWizard/ConnectionFlowHeader.tsx
- app/jenkins-for-jira-ui/src/components/CopiedToClipboard/CopyToClipboardContent.tsx
- app/jenkins-for-jira-ui/src/components/InfoPanel/InfoPanel.styles.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.styles.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.test.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.tsx
- app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.styles.tsx
- app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.tsx
- app/jenkins-for-jira-ui/src/components/ServerManagement/TopPanel/TopPanel.tsx
- app/jenkins-for-jira-ui/yarn.lock
See https://hello.atlassian.net/wiki/spaces/OTFS/pages/3274450234/J4J+config+uplift+--+checklist+items+from+blitz
> ARC-2831 address blitz items

- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectedJenkinsServers.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.styles.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsServerList/ConnectedServer/ConnectedServers.tsx
- app/src/common/types.ts
- app/src/storage/update-jenkins-server-state.test.ts
- app/src/storage/update-jenkins-server-state.ts
- app/src/webtrigger/handle-jenkins-request.ts
Display the environment names for pipeline events
But what if theres way too many environments?
> added env name to new page

- app/jenkins-for-jira-ui/package-lock.json
- app/jenkins-for-jira-ui/src/App.tsx
- app/package-lock.json
use the new allowed version of typography!
> try diff typo

- app/jenkins-for-jira-ui/src/components/ConnectionPanel/SetUpGuide.tsx
- app/jenkins-for-jira-ui/src/components/CopiedToClipboard/CopyToClipboardContent.tsx
Content changes...
**Why**
Don't ask
literally flip a fucking table if there are any more content changes.
> NONE apply more content changes

- app/jenkins-for-jira-ui/package.json
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectedJenkinsServers.test.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.styles.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.test.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/NotConnectedState.test.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/SetUpGuide.test.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionWizard/ConnectionWizard.styles.tsx
- app/jenkins-for-jira-ui/src/components/GlobalPage/GlobalPage.test.tsx
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelp.styles.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.styles.tsx
- app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.test.tsx
- app/jenkins-for-jira-ui/yarn.lock
General tidy up: removed class names that weren't being used, made sure tests names were consistent and all started with 'should blah blah', and removed 2 TODOs. I'd originally added these to add tests for rename and connection setting tests but all these handlers do is call history.push
**Why**
Code hygiene.
> NONE cleanup

- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelMain.tsx
> set conditional state to false on failure as well

- app/jenkins-for-jira-ui/package-lock.json
- app/jenkins-for-jira-ui/package.json
- app/jenkins-for-jira-ui/yarn.lock
> added history dependency

- app/jenkins-for-jira-ui/package.json
- app/jenkins-for-jira-ui/src/App.tsx
- app/jenkins-for-jira-ui/yarn.lock
- app/src/config/feature-flags.ts
> clean up feature flag stuff

- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelMain.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.tsx
- app/jenkins-for-jira-ui/src/components/ServerManagement/ServerManagement.tsx
Just some analytics tidy up - fixed one and removed an used attribute from 2 others.
> NONE - fix name and remove unused attr

- app/jenkins-for-jira-ui/package.json
- app/jenkins-for-jira-ui/yarn.lock
Added @babel/plugin-proposal-private-property-in-object as a dependency.
**Why**
Whenever we run yarn start/build we've started seeing this warning
> NONE add babel dependency

- app/jenkins-for-jira-ui/src/App.tsx
- app/jenkins-for-jira-ui/src/common/featureFlags.ts
- app/jenkins-for-jira-ui/src/common/types.ts
- app/jenkins-for-jira-ui/src/components/ConnectionComplete/ConnectionComplete.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.tsx
- app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.tsx
Part 2 of admin check. Addition of new feature flag and update to ParamTypes. I moved this out to a new file coz it's used in a bunch of places (and currently lives in part of the old flow) but didn't touch the references in the existing flow seeing we're going to delete all that code in the not-too-distant-future.
**Why**
Pulling more of the noise out from the 'meat' of changes. 
check_user_permissions
ARC-2807
Final PR
> ARC-2807 admin check global page

- app/package.json
- app/src/check-permissions.ts
- app/src/common/metric-names.ts
- app/src/resolvers.ts
- app/src/storage/connect-jenkins-server.test.ts
- app/src/storage/connect-jenkins-server.ts
- app/src/storage/disconnect-jenkins-server.test.ts
- app/src/storage/disconnect-jenkins-server.ts
- app/src/storage/get-all-jenkins-servers.test.ts
- app/src/storage/get-all-jenkins-servers.ts
- app/src/storage/get-jenkins-server-with-secret.ts
- app/src/storage/update-jenkins-server-state.test.ts
- app/src/storage/update-jenkins-server-state.ts
- app/src/webtrigger/handle-jenkins-request.test.ts
- app/src/webtrigger/handle-reset-jenkins-request.test.ts
- app/src/webtrigger/handle-reset-jenkins-request.ts
- app/src/webtrigger/webtrigger-utils.ts
- app/yarn.lock
Added more metrics. Don't be afraid of the number of file changes. Most are just metric additions, the rest are test updates.
**Why**
Coz our existing ones are lacking.
ARC-2288
Locally and staging
Ansheng to create charts :)
> ARC-2288 add metrics and update tests

- app/README.md
Update the app readme to help new starter to better set up and test.
**Why**
_Jira Issues_
_Include how to test if applicable_
> Update app readme

- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanel.styles.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/ConnectionPanelMain.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionPanel/SetUpGuide.tsx
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelpAction.tsx
- app/jenkins-for-jira-ui/src/components/SharePage/SharePage.test.tsx
- app/jenkins-for-jira-ui/src/components/SharePage/SharePage.tsx
Add "Share page" and "Learn more" button with their corresponding action in the setup guide.
Update Setup Guide text instruction
**Why**
Jenkins Phase 1.1 Design Improvements
ARC-2905
Run 'yarn test'
Manual testing in local dev to make sure UI is performing as expected.
This PR created SharePage component. There are 2 more places that has share page action but the share page action is not independent from the rest of the react component. Therefore, next step is to update the rest of the places to use SharePage component.
> Update Setup Guide UI 1.1

- app/jenkins-for-jira-ui/src/components/SharePage/SharePage.tsx
update the share text content
**Why**
Jenkins Phrase 1.1 Design Update
ARC-2911
yarn test &&
manual testing
> update share page text content

- app/src/storage/update-jenkins-server-state.ts
Have to check data exists before assigning it :cone-of-shame:
> send analytics before adding ipadress

- app/jenkins-for-jira-ui/src/components/ConnectionWizard/ConnectionWizard.styles.tsx
- app/jenkins-for-jira-ui/src/components/ConnectionWizard/ConnectionWizard.tsx
Update UI for the first step of connection wizard
**Why**
Jenkins Design Phrase 1.1 update 4.1
**Affected issues** 
ARC-2921
yarn test &
> ARC-2921 update screen for connection wizard

- app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.test.tsx
- app/jenkins-for-jira-ui/src/components/ServerNameForm/ServerNameForm.tsx
Update page 2 connection wizard
**Why**
Jenkins 1.1 Design Pharse
ARC-2920
yarn test &
manual testing in UI
> ARC-2920 update UI from server to connection in the wizard

- app/jenkins-for-jira-ui/src/GlobalStyles.styles.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.styles.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.test.tsx
- app/jenkins-for-jira-ui/src/components/JenkinsSetup/JenkinsSetup.tsx
Update connect wizard screen 3
**Why**
Jenkins Design Phrase Update 1.1
ARC-2922
yarn test & manul UI testing
Update Copy Buttons Logic and Appearance 4.3.2
> ARC-2922 update connect wizard screen part 1

- app/jenkins-for-jira-ui/src/App.tsx
- app/jenkins-for-jira-ui/src/common/featureFlags.ts
- app/jenkins-for-jira-ui/src/components/SharePage/SharePage.test.tsx
Ripping out the new flow feature flag :)
> removed new flow feature flag

- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelp.test.tsx
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelpAction.tsx
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelpDrawer.tsx
Update J4J to the new IPH server
**Why**
The copsi server is stale and can no longer push new content change
ARC-3020
Tested locally
> update IPH server change

- app/README.md
- app/jenkins-for-jira-ui/src/components/InProductHelpDrawer/InProductHelp.test.tsx
- app/src/webtrigger/handle-jenkins-request.test.ts
- app/src/webtrigger/handle-jenkins-request.ts
Fixing wording for "builds" in the UI
**Why**
Cause there are no environments for them
> Gua 708 fix unknown env for builds

- app/src/analytics/analytics-client.ts
- app/src/storage/update-jenkins-server-state.ts
Fixing CD
**Why**
Broken since long time 🤦
> GUA-708: fix deployment pipeline
